apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neudrive-agi-bar
  namespace: neudrive
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: neudrive.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: neudrive-server
                port:
                  number: 8080
