import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { setupUser } from './helpers'

test.describe('Bundle Sync', () => {
  test('generate sync token, preview json bundle, import and show history', async ({ page, request }) => {
    await setupUser(page, request)

    const bundlePath = path.join(os.tmpdir(), `pw-sync-${Date.now()}.ahub`)
    const bundle = {
      version: 'ahub.bundle/v1',
      created_at: new Date().toISOString(),
      source: 'playwright',
      mode: 'merge',
      profile: {
        preferences: 'Playwright sync preview',
      },
      skills: {
        'pw-sync-skill': {
          files: {
            'SKILL.md': '# PW Sync Skill\nGenerated by Playwright',
            'references/notes.md': 'fixture content',
          },
          binary_files: {},
        },
      },
      memory: [],
      stats: {
        total_skills: 1,
        total_files: 2,
        total_bytes: 64,
        binary_files: 0,
        profile_items: 1,
        memory_items: 0,
      },
    }
    fs.writeFileSync(bundlePath, JSON.stringify(bundle, null, 2))

    try {
      await page.goto('/data/sync')
      await page.getByRole('button', { name: '生成 Sync Token' }).click()
      await expect(page.getByText('当前 Token')).toBeVisible()

      await page.locator('input[type="file"]').setInputFiles(bundlePath)
      await page.getByRole('button', { name: 'Preview' }).click()
      await expect(page.getByText('Preview')).toBeVisible()
      await expect(page.getByText(/create/i)).toBeVisible()

      await page.getByRole('button', { name: '开始导入' }).click()
      await expect(page.getByText(/导入完成/)).toBeVisible({ timeout: 15000 })

      await expect(page.getByText(/import \/ json/)).toBeVisible({ timeout: 15000 })
    } finally {
      fs.unlinkSync(bundlePath)
    }
  })
})
