import { test, expect } from '@playwright/test'
import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { setupUser } from './helpers'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')

function writeJSONBundle(filePath: string, bundle: Record<string, unknown>) {
  fs.writeFileSync(filePath, JSON.stringify(bundle, null, 2))
}

function writeSkillSourceDir(skillName: string) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), `pw-sync-src-${Date.now()}`))
  const skillRoot = path.join(root, skillName)
  fs.mkdirSync(path.join(skillRoot, 'references'), { recursive: true })
  fs.writeFileSync(path.join(skillRoot, 'SKILL.md'), `# ${skillName}\nGenerated by Playwright`, 'utf8')
  fs.writeFileSync(path.join(skillRoot, 'references', 'notes.md'), 'archive fixture content', 'utf8')
  return root
}

test.describe('Bundle Sync', () => {
  test('preview mirror deletes with expanded detail list', async ({ page, request }) => {
    await setupUser(page, request)

    const initialBundlePath = path.join(os.tmpdir(), `pw-sync-initial-${Date.now()}.ahub`)
    const initialBundle = {
      version: 'ahub.bundle/v1',
      created_at: new Date().toISOString(),
      source: 'playwright',
      mode: 'merge',
      profile: {},
      skills: {
        'pw-sync-skill': {
          files: {
            'SKILL.md': '# PW Sync Skill\nGenerated by Playwright',
            'references/notes.md': 'fixture content',
          },
          binary_files: {},
        },
      },
      memory: [],
      stats: {
        total_skills: 1,
        total_files: 2,
        total_bytes: 64,
        binary_files: 0,
        profile_items: 0,
        memory_items: 0,
      },
    }
    const mirrorBundlePath = path.join(os.tmpdir(), `pw-sync-mirror-${Date.now()}.ahub`)
    const mirrorBundle = {
      ...initialBundle,
      mode: 'mirror',
      skills: {
        'pw-sync-skill': {
          files: {
            'SKILL.md': '# PW Sync Skill\nGenerated by Playwright',
          },
          binary_files: {},
        },
      },
      stats: {
        total_skills: 1,
        total_files: 1,
        total_bytes: 32,
        binary_files: 0,
        profile_items: 0,
        memory_items: 0,
      },
    }
    writeJSONBundle(initialBundlePath, initialBundle)
    writeJSONBundle(mirrorBundlePath, mirrorBundle)

    try {
      await page.goto('/data/sync')
      await page.getByRole('button', { name: '生成 Sync Token' }).click()
      await expect(page.getByText('当前 Token')).toBeVisible()

      await page.getByLabel('Bundle file').setInputFiles(initialBundlePath)
      await page.getByRole('button', { name: '开始导入' }).click()
      await expect(page.getByText(/导入完成/)).toBeVisible({ timeout: 15000 })
      await expect(page.getByText(/import \/ json/)).toBeVisible({ timeout: 15000 })

      await page.getByLabel('Bundle file').setInputFiles(mirrorBundlePath)
      await page.getByLabel('Import mode').selectOption('mirror')
      await page.getByRole('button', { name: 'Preview' }).click()
      await expect(page.locator('.data-sync-preview .data-record-title').filter({ hasText: 'Preview' })).toBeVisible()
      await expect(page.getByText('pw-sync-skill', { exact: true })).toBeVisible()
      await expect(page.getByText('/skills/pw-sync-skill/references/notes.md')).toBeVisible()
      await expect(page.getByText('只会影响 bundle 中声明的 skill')).toBeVisible()
      await expect(page.locator('.preview-action-delete').first()).toBeVisible()
    } finally {
      fs.unlinkSync(initialBundlePath)
      fs.unlinkSync(mirrorBundlePath)
    }
  })

  test('resume archive session from history', async ({ page, request }) => {
    const user = await setupUser(page, request)
    const sourceDir = writeSkillSourceDir('pw-archive-skill')
    const archivePath = path.join(os.tmpdir(), `pw-sync-${Date.now()}.ahubz`)

    execFileSync('python3', [
      path.join(ROOT, 'tools', 'ahub-sync.py'),
      'export',
      '--source',
      sourceDir,
      '--format',
      'archive',
      '-o',
      archivePath,
    ], { stdio: 'inherit' })

    const archiveBytes = fs.readFileSync(archivePath)
    const manifest = JSON.parse(execFileSync('python3', [
      '-c',
      [
        'import json, sys, zipfile',
        'with zipfile.ZipFile(sys.argv[1], "r") as zf:',
        '    print(zf.read("manifest.json").decode("utf-8"))',
      ].join('\n'),
      archivePath,
    ], { encoding: 'utf8' }))

    const syncTokenRes = await request.post('/api/tokens/sync', {
      headers: { Authorization: `Bearer ${user.token}` },
      data: { access: 'both', ttl_minutes: 30 },
    })
    const syncTokenBody = await syncTokenRes.json()
    const syncToken = syncTokenBody.data.token

    const startRes = await request.post('/agent/import/session', {
      headers: {
        Authorization: `Bearer ${syncToken}`,
        'Content-Type': 'application/json',
      },
      data: {
        transport_version: 'ahub.sync/v1',
        format: 'archive',
        mode: 'merge',
        manifest,
        archive_size_bytes: archiveBytes.length,
        archive_sha256: manifest.archive_sha256,
      },
    })
    expect(startRes.ok()).toBeTruthy()

    try {
      await page.goto('/data/sync')
      await page.getByRole('button', { name: '生成 Sync Token' }).click()
      await expect(page.getByText('当前 Token')).toBeVisible()
      await expect(page.locator('.token-list-prefix').filter({ hasText: /^session / })).toBeVisible({ timeout: 15000 })
      await page.getByRole('button', { name: '选择并继续这个 Session' }).click()
      await expect(page.locator('.alert-warn').filter({ hasText: '已选择继续未完成 session' })).toBeVisible()
      await page.getByLabel('Bundle file').setInputFiles(archivePath)
      await page.getByRole('button', { name: '开始导入' }).click()
      await expect(page.getByText(/导入完成/)).toBeVisible({ timeout: 20000 })
    } finally {
      fs.rmSync(sourceDir, { recursive: true, force: true })
      fs.unlinkSync(archivePath)
    }
  })
})
