import { useEffect, useMemo, useRef, useState } from 'react'
import LanguageToggle from '../components/LanguageToggle'
import { useI18n } from '../i18n'
import type { ImportResult } from '../api'
import { dataFileBrowseRoute } from './data/DataShared'

interface SkillsImportRequest {
  token: string
  platform: string
  error: 'missing_token' | ''
}

function parseSkillsImportRequest(search: string): SkillsImportRequest {
  const params = new URLSearchParams(search)
  const token = (params.get('token') || '').trim()
  const platform = (params.get('platform') || 'claude-web').trim() || 'claude-web'

  if (!token) {
    return {
      token: '',
      platform,
      error: 'missing_token',
    }
  }

  return {
    token,
    platform,
    error: '',
  }
}

function isZipFile(file: File) {
  const lowerName = file.name.toLowerCase()
  return lowerName.endsWith('.zip') || file.type === 'application/zip' || file.type === 'application/x-zip-compressed'
}

function formatFileSize(bytes: number, locale: 'zh-CN' | 'en') {
  if (!Number.isFinite(bytes) || bytes <= 0) return locale === 'zh-CN' ? '未知大小' : 'Unknown size'
  const units = ['B', 'KB', 'MB', 'GB']
  let value = bytes
  let unitIndex = 0
  while (value >= 1024 && unitIndex < units.length - 1) {
    value /= 1024
    unitIndex += 1
  }
  return `${value.toFixed(value >= 10 || unitIndex === 0 ? 0 : 1)} ${units[unitIndex]}`
}

function extractResponsePayload(xhr: XMLHttpRequest) {
  if (xhr.response && typeof xhr.response === 'object') {
    return xhr.response
  }
  const text = (() => {
    if (typeof xhr.response === 'string') {
      return xhr.response
    }
    if (xhr.responseType === '' || xhr.responseType === 'text') {
      return xhr.responseText
    }
    return ''
  })()
  if (!text) {
    return null
  }
  try {
    return JSON.parse(text)
  } catch {
    return null
  }
}

function uploadSkillsArchive(
  token: string,
  platform: string,
  file: File,
  onProgress: (percent: number) => void,
): Promise<ImportResult> {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest()
    const params = new URLSearchParams()
    if (platform) {
      params.set('platform', platform)
    }

    xhr.open('POST', `/agent/import/skills?${params.toString()}`)
    xhr.setRequestHeader('Authorization', `Bearer ${token}`)
    xhr.responseType = 'json'

    xhr.upload.onprogress = (event) => {
      if (!event.lengthComputable || event.total <= 0) return
      onProgress(Math.max(1, Math.min(99, Math.round((event.loaded / event.total) * 100))))
    }

    xhr.onerror = () => {
      reject(new Error('network error'))
    }

    xhr.onload = () => {
      const payload = extractResponsePayload(xhr)
      if (xhr.status >= 200 && xhr.status < 300) {
        onProgress(100)
        const data = payload && payload.ok === true && payload.data !== undefined ? payload.data : payload
        resolve(data as ImportResult)
        return
      }

      const message = payload?.message || payload?.error || xhr.statusText || 'upload failed'
      reject(new Error(message))
    }

    const formData = new FormData()
    formData.append('platform', platform)
    formData.append('file', file)
    xhr.send(formData)
  })
}

export default function SkillsImportPage() {
  const { locale, tx } = useI18n()
  const inputRef = useRef<HTMLInputElement | null>(null)
  const [request] = useState<SkillsImportRequest>(() => parseSkillsImportRequest(window.location.search))
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const [isDragging, setIsDragging] = useState(false)
  const [busy, setBusy] = useState(false)
  const [progress, setProgress] = useState(0)
  const [error, setError] = useState('')
  const [result, setResult] = useState<ImportResult | null>(null)
  const showUploadActions = Boolean(selectedFile) && (!result || busy)
  const dashboardSkillsHref = dataFileBrowseRoute('/skills')

  useEffect(() => {
    if (!request.token) return
    const params = new URLSearchParams(window.location.search)
    if (!params.has('token')) return
    params.delete('token')
    const nextSearch = params.toString()
    window.history.replaceState({}, '', `${window.location.pathname}${nextSearch ? `?${nextSearch}` : ''}`)
  }, [request.token])

  const requestError = useMemo(() => {
    if (request.error === 'missing_token') {
      return tx(
        '这个上传页面需要通过 Agent Hub 生成的带 token 链接打开。',
        'This upload page must be opened through a tokenized link generated by Agent Hub.',
      )
    }
    return ''
  }, [request.error, tx])

  const selectFile = (file: File | null) => {
    if (!file) return

    if (!isZipFile(file)) {
      setError(tx('请上传 `.zip` 格式的 skills archive。', 'Please upload a `.zip` skills archive.'))
      setSelectedFile(null)
      setResult(null)
      setProgress(0)
      return
    }

    setSelectedFile(file)
    setError('')
    setResult(null)
    setProgress(0)
  }

  const handleUpload = async () => {
    if (!request.token || !selectedFile || busy) return

    setBusy(true)
    setError('')
    setResult(null)
    setProgress(0)

    try {
      const uploaded = await uploadSkillsArchive(request.token, request.platform, selectedFile, setProgress)
      setResult(uploaded)
      if (inputRef.current) {
        inputRef.current.value = ''
      }
    } catch (err: any) {
      const message = err?.message === 'network error'
        ? tx('上传过程中发生网络错误，请重试。', 'A network error occurred during upload. Please try again.')
        : (err?.message || tx('上传失败', 'Upload failed'))
      setError(message)
      setProgress(0)
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="skills-upload-page">
      <div className="skills-upload-card">
        <div className="login-card-header">
          <LanguageToggle />
        </div>
        <div className="sync-login-eyebrow">Agent Hub Skills</div>
        <h1 className="login-title">{tx('上传 Skills Zip', 'Upload skills zip')}</h1>
        <p className="login-desc">
          {tx(
            '把完整的 skills zip 上传到 Agent Hub。页面会把内容导入 `/skills` 根目录，并反馈导入了哪些 skills。',
            'Upload a complete skills zip into Agent Hub. The page imports it into the `/skills` root and reports which skills were imported.',
          )}
        </p>

        <div className="sync-login-summary">
          <div className="sync-login-summary-row">
            <span>{tx('目标目录', 'Target root')}</span>
            <strong>/skills</strong>
          </div>
          <div className="sync-login-summary-row">
            <span>{tx('来源平台', 'Platform')}</span>
            <strong>{request.platform}</strong>
          </div>
        </div>

        {(requestError || error) && (
          <div className="alert alert-error">
            {requestError || error}
          </div>
        )}

        <div
          className={`skills-upload-dropzone${isDragging ? ' is-dragging' : ''}${requestError || busy ? ' is-disabled' : ''}`}
          onClick={() => {
            if (!requestError && !busy) {
              inputRef.current?.click()
            }
          }}
          onDragOver={(event) => {
            if (requestError || busy) return
            event.preventDefault()
            setIsDragging(true)
          }}
          onDragLeave={(event) => {
            event.preventDefault()
            setIsDragging(false)
          }}
          onDrop={(event) => {
            if (requestError || busy) return
            event.preventDefault()
            setIsDragging(false)
            const file = event.dataTransfer.files?.[0] || null
            selectFile(file)
          }}
          role="button"
          tabIndex={requestError || busy ? -1 : 0}
          onKeyDown={(event) => {
            if (requestError || busy) return
            if (event.key === 'Enter' || event.key === ' ') {
              event.preventDefault()
              inputRef.current?.click()
            }
          }}
        >
          <input
            ref={inputRef}
            type="file"
            accept=".zip,application/zip,application/x-zip-compressed"
            className="skills-upload-input"
            onChange={(event) => {
              const file = event.target.files?.[0] || null
              event.target.value = ''
              selectFile(file)
            }}
            disabled={!!requestError || busy}
          />
          <div className="skills-upload-dropzone-title">
            {tx('拖拽 zip 到这里，或点击选择文件', 'Drag a zip here, or click to choose a file')}
          </div>
          <div className="skills-upload-dropzone-copy">
            {tx(
              '请上传完整的 skills archive，不要只包含 `SKILL.md`。',
              'Upload a complete skills archive, not a `SKILL.md`-only shortcut.',
            )}
          </div>
        </div>

        {selectedFile && (
          <div className="skills-upload-file-meta">
            <div className="data-record-title">{selectedFile.name}</div>
            <div className="data-record-secondary">
              {tx('文件大小：', 'File size: ')}{formatFileSize(selectedFile.size, locale)}
            </div>
          </div>
        )}

        {showUploadActions && (
          <div className="skills-upload-actions">
            <button
              className="btn btn-primary"
              disabled={!selectedFile || !!requestError || busy}
              onClick={() => { void handleUpload() }}
            >
              {busy ? tx('上传中...', 'Uploading...') : tx('开始上传', 'Start upload')}
            </button>
            <button
              className="btn"
              disabled={busy}
              onClick={() => {
                setSelectedFile(null)
                setResult(null)
                setError('')
                setProgress(0)
                if (inputRef.current) {
                  inputRef.current.value = ''
                }
              }}
            >
              {tx('清空', 'Clear')}
            </button>
          </div>
        )}

        {(busy || progress > 0) && (
          <div className="skills-upload-progress">
            <div className="skills-upload-progress-bar">
              <div className="skills-upload-progress-fill" style={{ width: `${progress}%` }} />
            </div>
            <div className="data-record-secondary">
              {busy && progress >= 99
                ? tx('文件已上传，正在导入 skills...', 'Upload finished. Importing skills...')
                : tx(`上传进度：${progress}%`, `Upload progress: ${progress}%`)}
            </div>
          </div>
        )}

        {result && (
          <div className="skills-upload-results">
            <div className="alert alert-success">
              {tx(
                `上传完成，成功导入 ${result.imported} 个文件。`,
                `Upload complete. Imported ${result.imported} files.`,
              )}
            </div>

            <div className="sync-login-summary">
              <div className="sync-login-summary-row">
                <span>{tx('导入文件', 'Imported files')}</span>
                <strong>{result.imported}</strong>
              </div>
              <div className="sync-login-summary-row">
                <span>{tx('跳过文件', 'Skipped files')}</span>
                <strong>{result.skipped}</strong>
              </div>
              <div className="sync-login-summary-row">
                <span>{tx('导入 skills', 'Imported skills')}</span>
                <strong>{result.skills?.length || 0}</strong>
              </div>
            </div>

            {result.skills && result.skills.length > 0 && (
              <div className="skills-upload-skill-list">
                {result.skills.map((skill) => (
                  <span key={skill} className="skills-upload-skill-chip">{skill}</span>
                ))}
              </div>
            )}

            {result.errors && result.errors.length > 0 && (
              <div className="alert alert-warn">
                <div className="data-record-title">{tx('部分文件未导入', 'Some files were not imported')}</div>
                <ul className="skills-upload-error-list">
                  {result.errors.map((entry) => (
                    <li key={entry}>{entry}</li>
                  ))}
                </ul>
              </div>
            )}

            <div className="skills-upload-actions">
              <button
                className="btn btn-primary"
                onClick={() => {
                  window.location.assign(dashboardSkillsHref)
                }}
              >
                {tx('去 Dashboard 查看', 'Open dashboard')}
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
